#----------------------------------------------------------------------
# This file was generated by C:/Users/Marshall/Desktop/note/utils/encode_bitmap_util.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

empty_note = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAFzklEQVR4AeVb3XHUMBBOCZRA'
    b'CXQQOoCXRH6DDjgHeA4dkA64DqCD5IGTZ3jJdZDrINcBzCdL9kpaSSvfj+9CZjwnWbK0+2n3'
    b'25XsXFzs+a/V6lOr1VOr1d/ctdDq5+K+eb3n6ecd7malfuSUZtqev/65ejOv1HuafdE1HxkF'
    b'YQWbVjfLVjcPifanPYmwn2GwIovu+taYqFb3C//6+Vlfv+dm4hVslrQvxm612oZAfOmat7Sf'
    b'K99o9T2Yv5enu75tf19/WNy/f+X67vyLwaB0KFxU79Samyzqp9WWE/Bm1XwL++JeOCZACfsx'
    b'9efUgoTjZesQtF2pR2aCkMi2MHVusPjZ5oHrxynGAWBkSruNJ1dKJm5+9l7vo5a1O7VOmST7'
    b'sL0ZA6BY3+a4ggMgNxfACS1pckTpkR6Vz02ca2MA+LvQakGfsXNFIbIWADcmzJ/Me+fuV/3S'
    b'FdnFn4ggvnmCV0BYIC6tnrl+UwGAom2n1nZM1uKKYFBTmmxGEKSQ+OTadwLAhNjegovKch0o'
    b'AFw7d6/VV5fxlc/88gAggfLHlC7GFPk9nWoGQFzOKXKAtqdSplgjv6e4q0gHoFxxAEU93gjG'
    b'z/q2VH6nb/QrHaDV6lcgWE7ovbblrEAqP1XcZKQr9Q7EfCEdoNXqbi4AED6pArQslR/PmGik'
    b'1T3VQwwASInL4+lgBypn47sEAJsvRPkH9BEDAASxEkhuMOkxLklGmgMAi4bNVHphmocqAKjp'
    b'nUo5BYAlbTbxGgF5gQDASqUHMwDvRVmA2WvIdrUmSpm9SsqETsXES3IYpbEfwFWhPNzAcMy5'
    b'AwCAoAiu0bdlaTnAE7uA8S17RJXa1dUKkOoP5oYf5xIgZxkmqel3mQXCi0DZmjGkFkD7pQTf'
    b'/33+VMkpb3OTWsVtlmrHpoq5gblf42smG0ye7u4v/TV7/GaZswAjT6XP0wWC3lUWwIEy571a'
    b'wqPKozwc/kgtYE5lw7mlcT5UmtYH6zo3ABC7qSJMGe8dSrzQEyCQPScAhKFOsG0n5HouAFgS'
    b'zq6s1YXb9XkEjX6DW50NAMW3Vs2S6sK4xgDCQIDn4gJFv+/U2iZEg5I5AGBNZ2MBgmRn2/fB'
    b'G+go24sBCd9tUrMZUDmhQv5Ao9/QCMnRguG/sRZHAZiY6O2xZBUkfVbqsXQM78isBBK1DByU'
    b'eOsrtYA5D0WpAmO5D2WVx/XGXSYBgIcsGf3qP4bAnuCA1/jOL/Zj++2BDY3FsAfQsNAe+TkU'
    b'pBbg+h/jtxTzXRijso+WERJhs+xJ8uoSXBHJTweJGme6QWViFDPH5DY6cNbR3+vUGhxi9w0m'
    b'gXLAeWrRybyGmSrZ1SchbAohn4UL0AUJV9/t4OrCnnMJkv/TxaUT0vtzlVMfWUJOJ9OUs4Ao'
    b'/LnBTgkA+Gi46qbum35pO8zxAvvFmsHglABIvYF2pp/lh0xyRa3HLfzweyoAWOWi1aPCT0zG'
    b'NoOyXKEWABdTw09adq3bj6hCADaOuWt2e9SN2NhPgZACYJlXlHVRAXYpU+Fr8n03J7UeqrNX'
    b'lgJQ3JNnfNAJVPc77tqS5JiecyNSHkhIAUBfmCH6H+IKDjIH1rbcULa8Tq2xSI4wvVXOVWoA'
    b'yI2zS1uY2EARNx6VL2VB5st28yHm1aXjDPd88ZdOUOx8oA5e+KMxv/8sJyTGUn1LuaMo8twA'
    b'hJsaKnw18cENav8NhwJQ/XAR3nIH70t1PRJf5UEHrCL7MVVSEjoRu11MPrl7Q7D6IfFl3wEM'
    b'fDDx8/5Bei8DW6nHoeEIBc/6CPFZUsQbnujfawbFtdokNzi1sntmuFKP1A9rx6rpP4Q+Qnzh'
    b'87ASyIMLgMFKq0NdOGhYN1aQP4MrMS/bnlsh6nrHAjzU26v3riB8uZDOwCIgUiCMoW8kPk+g'
    b'uSou2xv/12/3k9/QZAnvDMQ3l76zzOvMn2Z8swgy16TG/DPEN5dcR5sX7H8SxHc0jclEjmzJ'
    b'rf+rCEIECKei9T9/5BgxkQNCCwAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
more = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAU0lEQVQ4T2NkoBJgpJI5DKMG'
    b'EQ5JmoVRA9RuGA3iEiWG7KIuBgaGUqhB3QwMDGUMDAzEiqFEP7GasKnDSEdEeQObd2kW2ITj'
    b'GYeKURcRDjqqhREALUcSE79Y0AQAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
sort = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAvElEQVQ4T7WTsQ0CMQxF7ezA'
    b'ChTJr2lhAGrWAWahpD3RcuzgfYwcXU4gBZJDJl0k+/nb/mZyeuzEof+AACgRnUXkZEoB7HoU'
    b'i8j4pqgCMuCxAcuFWyAfRT1tlZivitxAAGxG2wrwURbSpcgN5NbaIlCMMYUQVlPS3QxJRKP9'
    b'mVlVdV6IGe8TPAellDZEdGHm9RR4FZEDADNjdvmr42uwuZqdAzPfVHUwSO1EmopKBQB7ERmW'
    b'zKa6/l8A7qAnNiVoE+4+6y4AAAAASUVORK5CYII=')

#----------------------------------------------------------------------
tool_background = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAABgElEQVQ4T5XUMUjXURDA8Y9L'
    b'CNbQ4tLiUIYEDo0uBYFQLblLoE0RUVFBCJGCCCERCDbp6CyCRkFQTlLgFEUU5BItQQ7ZkIty'
    b'ecLz5/ubPfjxe3fv7vvu3d17bXbGNUyiA0dS96/fJn7jPmbbcD6/0Yrn60L3NTdsmoXfmwCt'
    b'43gF0o+XDX07/lRs1wMUIdaO8woXGk4PMV4BbQYoQmseqwtr6fABZ3K+gWMV0FYr0DNcT4cx'
    b'3MXRlAcx14C1BG0VhhHNPQyl7j16DwO6jadpuII+XMTzwjkqvVzI1Yg+41QaPcDjnH/DiZwv'
    b'4MpBoEtYKgx68CnlKdws1rrxJeV9ES3ici6+wNtGLh4VcoBv1UAnix0qFa6qopJxTfZEFAmO'
    b'RP/P2M3hHtCvoleij260IJat8T0L8BcUd+cOphu987EFaBbDxdpVzAToZ16Hs7n4A50HnO90'
    b'UckwexftEqAnCEjZYLUnpWRH9cI3xjms7grRqfP5sE0cMtsjWbGBeI+2AQ4+VqXbi/B7AAAA'
    b'AElFTkSuQmCC')

#----------------------------------------------------------------------
tool_bold = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAABmUlEQVQ4T62Tv0scQRTHv9/b'
    b'A6u0giDkEkTu2NkiJG0ggYBgYXdWaiNoJ9imiSmSNPkLQrp0uT6m8wQxlbDcvCnEg7PR5jyx'
    b'j/DCHLvL7CbkLkemmjfvvc/7OcR/Osw5xpiv2X0IYKiqD0k2gjjH/k7SWWs71fghaBPAYwAH'
    b'uZGq7pNMST5R1TUALzJdR0TWQ1gBCjLTwOCliHQDnQ/yJpPPRORZrvsNFMfxICipBGo2m416'
    b'vT7InWu1WrPX652PS67Waow5CkoogVqt1kIURdd/yngS6K2IFD1LkqStqvlQICKF/0QQgLxH'
    b'TwF8zLJ5LSIfJjU7LO0KwAWABwA8yJ9Tku+std+mBpFctdYeeoc4jpdIvgfQ9rKq+vcN59zt'
    b'NM0u9cg7GGO+A1jJYJ+cc7uzgopdUtVL59yjmUCVyQ1FZH4mkDHmM4DtrNEnIvL8n0HVPQKw'
    b'JSJfSqAkSXZU9VU+lSyi3yGrqvckFwNdn+RePtESKPsa/u0ngJGq3pAcjY3IZVWdI9kH8COK'
    b'om6apnd/3aPq35tW/gV5Gr0TXgB5sQAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
tool_bold_active = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAABtklEQVQ4T62UzysEYRjHv8+7'
    b'clBY2pQ4WHbswUkuSopSbsqBmyQlNShnB6vExY0dKX8BF+XitnuQclAuWF6ykq1N7SwHETOP'
    b'JjtjrN3Jbt7TvO/z9Hl+fJ95CP90yObUReUOAJPAaQa9AGgGodkdhxkngpCAwFFmWjl32xyQ'
    b'f0OOgdBKQMR2YMY8GKdCoJMJQ2D0OTYT/dlZJW7fHZArMy7m7F+/jJAQizl7qraqoi05EXy1'
    b'7qWBNi9ayKy4dbLwocMusSRQYCvZaHy8p2yQaSD0NKfcFM5Ik49gBCwj5/WhXpMjzLBEsc6x'
    b'rirdHj26SgAUtkG2oxDUxeA1BqUJvEsGFjJzynNxkCYPwejJOTyAIIlRzUBX7u0FjGV9Rlkt'
    b'KL+jmiZjtszu0mqi1yEfeAXASM43RqDxjBq6L9ajgiBXoAMwBr/utKeroeGyQPmzpKtKU1mg'
    b'POUedVVpKAvkj8ptAia/SuNDXW3v/QPIXMrOhp1/Ly+bH3PmTHa9dj3FzAMuVaxA+0S4MRlM'
    b'1jb4VuyMfBh1b4DvNaLJGDElTdO4c8/Hr28fTvFWGc/OB7Oec+QJ8TB+ArCo5ROvP+iwAAAA'
    b'AElFTkSuQmCC')

#----------------------------------------------------------------------
tool_code_block = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAlklEQVQ4T93UMQ5BURBG4e9t'
    b'Q6WxDwoWYANWQKX31EqNls4KlOxEaQlKMsULeSE3ZApx20nO3PNPZipJr0rieAUaY4rBmyZH'
    b'7LF5rrdBK8xxKoD6mGHdwNqgG5aoC8pRX/Aw+m1QF+cP1Tq4RAyNWjgP0cMEh0JGI+xwxTYy'
    b'TQfFB1LUGpM/HX/opa1IwFKW9uurknaP7hd1MhMUGuXrAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
tool_code_block_active = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAzElEQVQ4T2NkoBJgpJI5DBgG'
    b'ia1+HMTIwJD7MlTWEZsl4qsf7//PyLjyVYjMDGR5FIMkVj/u/s/AUMLAwHAAn0EMDAwODAwM'
    b'eS9DZSfDDEMxSHz14/////1rfBUu34DPy2IrHzYwMjHVvwyVhesfxAZJLL+v8J+F5T4pXvvL'
    b'xCH1Jlj0OSgYwF6D+tmVgYFBlZGBIf5FqOx2vGG0+pEb43+GRQxMTN////27EBSm1DUIZDtV'
    b'vAbzxjCNfnA4USuLgJMCNTItJUUK1cojAPQnrhOyLoKKAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
tool_color = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAABP0lEQVQ4T63UQShlURzH8c9b'
    b'WI2ysGKhFLLR2LEjTYrMbtJMNpNZTayUkg0pKQtWpBSbSU12Jo1oSkqxJCUlOzZKNmqSoqPz'
    b'6nZ7t/uenM39d/6/3/f+zzn/cwreaRTK4ExHzQ6OsvR5oDrcRPNvfH0raB7jCXMVnkrB8ip6'
    b'RDDvohejWKoUNIA/OMcCVnGJ5kpB/9CDmQi6xgd04jgNy1paI66iuA1nWMf3+B0uFxSOfAqh'
    b'qk/R1I/tGFfjIQnLqugeNfiJlYThAi0YwXIe6As28R8NuE0YZjGJU3zMA23hM/Yzmq87znfh'
    b'oKhJL601HncZN8cafmSB5jCBvwhdXWo0xZ4KuVrchSBdUeiVegzGfcqq7DkmxrCYBg3hVxTk'
    b'XZ0NfMMJ2tOg4nMR5pNxqao60BcTh9jL+3M5m/6qeQER2DUTdFW7vQAAAABJRU5ErkJggg==')

